services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: healthstur-backend
    ports:
      - 8000:8000
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
